baseURL = "https://www.andrejkovacevic.com/"
languageCode = "hr"
defaultContentLanguage = "hr"
title = "Andrej Kovačević"
theme = "PaperMod"

[params]
hideFooter = false
defaultTheme = "auto"
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "Videoigre kao kognitivni medij"
subtitle = "Igre promatram kao kognitivne sustave, kulturne artefakte i medij transformativnog iskustva."
imageUrl = "/img/andrej_kovacevic.png"
imageTitle = "Andrej Kovačević"

[menu]

[[menu.main]]
name = "Tekstovi"
url = "/writing/"
weight = 10

[[menu.main]]
name = "Projekti"
url = "/projects/"
weight = 20

[[menu.main]]
name = "O meni"
url = "/about/"
weight = 30

[[menu.main]]
name = "Trenutno"
url = "/now/"
weight = 40
